### ISSUE TITLE
Version von Easy Controls

### ISSUE THREAD

**Issue by viktor-c** [KLVN/ioBroker_Helios-KWL#1]
Hallo! Ich bin auf der Suche nach einer zentralen Lüftung, welche sich mit ioBroker leicht einbinden lässt. Helios scheint die Möglichkeit zu geben über den Webserver die Gerätsteuerung zu erlauben. 
Helios wirbt mit einem bahnbrechendem System, Easy Controls v3. Ist die hier sich befindende Integration mit ioBroker kompatibel mit der "neuen" Version von easy Controls? 
Vielen Dank!

**Comment by KLVN** [comment]
Moin, zu diesem Zeitpunkt kann ich dir nicht sagen, ob dieses Skript mit easyControls 3.0 funktioniert. Meine Anlage ist etwas in die Jahre gekommen und bekommt auch kein Update mehr von v2.27 - ich habe auch keinen Zugriff auf eine neue Anlage mit v3.
Wenn ich mir so die Broschüre durchlese, scheint v3 aber nicht sonderlich bahnbrechend zu sein, weil vieles davon auch schon mit v2 möglich ist. Lediglich das Touch-Bedienelement und die kabellose Verbindung zu weiteren Sensoren sind neu. Es könnte also sein, dass dieses Skript tatsächlich noch mit v3 funktioniert, wenn Helios nicht allzu viel "unter der Haube" geändert hat.
