### ISSUE TITLE
Zusätzliche Datenpunkte

### ISSUE THREAD

**Issue by Sergej569** [KLVN/ioBroker_Helios-KWL#2]
Hallo, wie bekomme ich zusätzliche Datenpunkte ausgelesen die auf der Konfiguration Seite von Easycontrol sind. Ich bekomme immer "null" angezeigt. 

Grüße

**Comment by KLVN** [comment]
Moin, im ioBroker-Forum habe ich zwei kurze Beiträge dazu:
1. https://forum.iobroker.net/topic/24769/gel%C3%B6st-helios-kwl-zugriff-auf-xml/40?_=1653214438272
2. https://forum.iobroker.net/topic/24769/gel%C3%B6st-helios-kwl-zugriff-auf-xml/60?_=1653214571145

Wenn du die Register-ID schon kennst, kannst du Punkt 1 überspringen. In Punkt 2 wird erklärt, dass du in folgender Zeile ggfs. noch eine weitere Zahl eintragen musst, falls sich deine Register-ID auf einer anderen Konfigurations-Seite befindet.

https://github.com/KLVN/ioBroker_Helios-KWL/blob/e844b070ebc09a1d7ebe41d01cf53c5efa11ca15/helios.js#L74-L75

**Comment by Sergej569** [comment]
Hallo, danke.
